version: "3.3"

services:
  agendamedica.db:
    container_name: agendamedica.db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1434:1434
    environment:
      SA_PASSWORD: "12345678"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    